#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Creado por: Elsoberanox - https://www.youtube.com/c/JuegosenLinux"
TITLE="www.juegosenlinux.site"
MENU="Forager - Elsoberanox"

OPTIONS=(1 "Instalar Forager"
         2 "Desinstalar"
         3 "Ver mas ports"
         4 "Salir")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
sudo cp winetricks /usr/bin/
sudo chmod +x badown
./badown https://www.mediafire.com/file/zx5sikgjlw1dxmk/wineson.7z/file
7z x wineson.7z -psmiterganks13
sudo rm -R wineson.7z
sudo mv wineson /opt/
./badown https://www.mediafire.com/file/kg5e92uyvwkjh8o/f0R4G3R.v4.1.8.rar/file
unrar x f0R4G3R.v4.1.8.rar 
sudo rm -R f0R4G3R.v4.1.8.rar
sudo mv Forager\ v4.1.8-PiviGames.blog/ Forager-linux
mkdir $HOME/Juegos/
sudo mv Forager-linux $HOME/Juegos/
echo -e "cd $HOME/Juegos/Forager-linux/\nexport PATH=/opt/wineson/bin/\nwine Forager.exe" >> forager-bin
sudo chmod +x forager-bin
sudo mv forager-bin /usr/bin/
wget https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c52795fd-f7db-44f1-9d90-72dc3bd34c66/de1xqcd-34304f5e-5e67-441f-8f56-a75571ca29df.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2M1Mjc5NWZkLWY3ZGItNDRmMS05ZDkwLTcyZGMzYmQzNGM2NlwvZGUxeHFjZC0zNDMwNGY1ZS01ZTY3LTQ0MWYtOGY1Ni1hNzU1NzFjYTI5ZGYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.R75dIngJ7RODNY1OMfSaRLz-KeB-K8_TcB6_dWIE-68 -O foragerlinux.png
sudo mv foragerlinux.png /opt/
echo -e "[Desktop Entry]\n Version=1.0\n Type=Application\n Name=Forager Linux\n Comment=forager-bin\n Icon=/opt/foragerlinux.png\n Exec=forager-bin\n Categories=Game;" >> Forager.desktop
sudo chmod +x Forager.desktop
sudo mv Forager.desktop $HOME/.local/share/applications
xdg-desktop-menu forceupdate

            ;;
        2)
sudo rm -R /usr/bin/winetricks
sudo rm -R /opt/wineson
sudo rm -R /usr/bin/forager-bin
sudo rm -R /opt/foragerlinux.png
sudo rm -R $HOME/Juegos/Forager-linux
sudo rm -R $HOME/.local/share/applications/Forager.desktop
xdg-desktop-menu forceupdate

            ;;
        3)
            xdg-open https://www.juegosenlinux.site/
            ;;
            
                    3)
            exit
            ;;
esac
